name: Deploy to cPanel

on:
  push:
    branches:
      - master  # or 'master', depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up FTP details
        run: |
          echo "FTP_USERNAME=${{ secrets.FTP_USERNAME }}" >> $GITHUB_ENV
          echo "FTP_PASSWORD=${{ secrets.FTP_PASSWORD }}" >> $GITHUB_ENV
          echo "FTP_HOST=ftp.ballhub.online

      - name: Deploy files to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ftp.ballhub.online
          username: ${{ env.FTP_USERNAME }}
          password: ${{ env.FTP_PASSWORD }}
          local-dir: ./dist  # Path to your local build directory (React/Vite build folder)
          remote-dir: public_html  # Change to your cPanel deployment folder
